### ISSUE TITLE
Border size isn't counted in

### ISSUE THREAD

**Issue by dodas** [phegman/v-show-slide#2]
Hi, thanks for your component.
I just noticed one issue: when the toggled element has some `border` set, the height will go smoothly up to "height" of element without border, then instantly jump to real "full" height.

`el.scrollHeight` probably doesn't count in borders...
To overcome this, we would probably need to use `getComputedStyle()` to get actual border size and add it to `el.scrollHeight`.

Should I do an PR?

**Comment by phegman** [comment]
Hmm interesting, I will have to look into that when I have a spare minute. My first thought would be to continue to use `el.scrollHeight` and then check if the element has a border and add that to the calculation. I don't think `getComputedStyle()` will work because the height is set to `0`. Feel free to open a PR if you want to play around with the implementation!

Cheers,
Pete

**Comment by phegman** [comment]
The jump should be fixed in the latest release. However animating an element with a border still doesn't look very good as the border appears/disappears without any easing. I would suggest adding a "border" to the inside of the element using a styled `div` or CSS pseudo element. Something like this should work:

```css
.sliding-element::after {
  content: "";
  display: block;
  width: 100%;
  height: 5px;
  background-color: red;
}
```
